<?php

$themename  = "Devster";
$shortname  = "devster";

$display_options = array("pages","posts");
$categories_list = get_categories('hide_empty=0');

$categories = array();
foreach ($categories_list as $catlist) {
	$categories[$catlist->cat_ID] = $catlist->cat_name;
}

$listpages = array();
$pagelist = get_pages('parent=0');
foreach ($pagelist as $plist ) {
  $listpages[$plist->ID] = $plist->post_title;
}

$color_options = array("Default","Blue-Aurora","Galaxy","Grunge","Wood");

$num_options = array("2","3","4","5","6","7","8","9","10");

$options = array (
  array(	"name" => "显示选项",
					"type" => "heading"),
  array(	"name" => "配色方案",
  					"desc" => "选择配色方案, 默认是白色.",
  					"id" => $shortname."_style",
      			"std" => "Default",
      			"type" => "select",
      			"options" => $color_options),					
  array(  "name" => "自定义Logo图片地址",
        "desc" => "填入Logo图片地址，推荐使用144x51像素的图片",
        "id" => $shortname."_logo",
        "std" => "",
        "type" => "text"),               
  array(	"name" => "首页幻灯片设置",
					"type" => "heading"),
  array(	"name" => "选择要显示在幻灯片中的文章类别",
          "desc" => "请选择类别",
            "id" => $shortname."_featured_cat",
            "std" => "",
            "type" => "select",
            "options" => $categories),
	array(	"name" => "幻灯片中显示的文章数量",
			"desc" => "选择您想在幻灯片中显示的文章数量",
			"id" => $shortname."_featured_number",
			"std" => "2",
			"type" => "select",
			"options" => $num_options),
	array(	"name" => "幻灯片放映的速度，单位ms, 比如: 4000",
			"desc" => "填入幻灯片放映的速度",
            "id" => $shortname."_slideshowspeed",
            "type" => "text"),            	
	array(	"name" => "标题",
			"desc" => "幻灯片的标题",
            "id" => $shortname."_slide_title",
            "type" => "text"),
	array(	"name" => "简要描述",
			"desc" => "请填入幻灯片的简短描述(支持html标签)",
            "id" => $shortname."_slide_desc",
            "type" => "textarea"),            
  array(	"name" => "站点描述",
					"type" => "heading"),			
	array(	"name" => "标题",
			"desc" => "请填入站点标题",
            "id" => $shortname."_site_title",
            "type" => "text"),
	array(	"name" => "简介",
			"desc" => "请填入站点简介",
            "id" => $shortname."_site_desc",
            "type" => "textarea"),
  array(	"name" => "Contact页面设置，您的联系方式",
					"type" => "heading"),
	array(	"name" => "地址",
			"desc" => "请填入公司地址",
			"id" => $shortname."_info_address",
			"type" => "text"),
	array(	"name" => "电话",
			"desc" => "请填入公司联系电话",
			"id" => $shortname."_info_phone",
			"type" => "text"),
	array(	"name" => "传真",
			"desc" => "请填入公司传真",
			"id" => $shortname."_info_fax",
			"type" => "text"),			
	array(	"name" => "邮箱",
			"desc" => "请填入公司邮箱",
			"id" => $shortname."_info_email",
			"type" => "text"),
  array(  "name" => "联系方式页面中，您公司所在位置的地图图片地址",
        "desc" => "请填入地图图片的地址，推荐使用281x224 像素的图片",
        "id" => $shortname."_mapimage",
        "std" => "",
        "type" => "text"),            			
  array(	"name" => "菜单栏选项",
					"type" => "heading"),
  array( "name" => "从菜单中移除某页面Exclude pages navigation",
          "desc" => "请填入您不想在菜单中显示的页面的 <a href='http://codex.wordpress.org/wp_list_pages#Include_Pages_in_List'>ID</a>，用逗号隔开 (比如. 1,2,3,4)",
        "id" => $shortname."_exclude_pages",
        "std" => "",
        "type" => "text"),
  array(	"name" => "首页底部页面部分设置",
					"type" => "heading"),    
  array(	"name" => "About页面的ID",
          "desc" => "请选择About页面的ID",
            "id" => $shortname."_about_pid",
            "std" => "",
            "type" => "select",
            "options" => $listpages),
  array(	"name" => "Services(最顶层) 页面的ID",
          "desc" => "请选择Services页面的ID",
            "id" => $shortname."_services_pid",
            "std" => "",
            "type" => "select",
            "options" => $listpages),
  array(	"name" => "Contact页面的ID",
          "desc" => "请选择Contact页面的ID",
            "id" => $shortname."_contact_pid",
            "std" => "",
            "type" => "select",
            "options" => $listpages),
  array(	"name" => "文章分类设置",
					"type" => "heading"),
  array(	"name" => "Testimonial的文章分类ID",
          "desc" => "选择Testimonial页面的文章分类ID",
            "id" => $shortname."_testimonial_cid",
            "std" => "",
            "type" => "select",
            "options" => $categories),
  array(	"name" => "产品展示(Portfolio)页面设置",
					"type" => "heading"),
  array(	"name" => "Portfolio的文章分类ID",
          "desc" => "选择Portfolio页面的文章分类ID",
            "id" => $shortname."_portfolio_cid",
            "std" => "",
            "type" => "select",
            "options" => $categories),
  array(	"name" => "Portfolio页面底部的联系方式图片地址",
          "desc" => "请填入您想在Portfolio页面底部显示的联系方式图片的地址，点击这张图片将自动链接到Contact页面",
            "id" => $shortname."_getquote_image",
            "std" => "",
            "type" => "text"),      
  array(	"name" => "文章Blog设置部分",
					"type" => "heading"),        
  array(	"name" => "Blog的文章分类ID",
          "desc" => "选择Blog页面的文章分类ID",
            "id" => $shortname."_news_cid",
            "std" => "",
            "type" => "select",
            "options" => $categories),
	array(	"name" => "Blog页面显示的文章数量",
			"desc" => "请填入每页要显示的文章数量.",
			"id" => $shortname."_blog_num",
			"std" => "2",
			"type" => "select",
			"options" => $num_options),
	array(	"name" => "文章摘要的字数",
			"desc" => "请填入文章摘要的字数",
            "id" => $shortname."_blogtext",
            "type" => "text"),				
  array(	"name" => "sns账户设置",
					"type" => "heading"),
	array(	"name" => "Feedburner ID",
			"desc" => "请填入你的Feedburner ID",
			"id" => $shortname."_feedburner_id",
			"std" => "",
			"type" => "text"),
	array(	"name" => "Twitter ID",
			"desc" => "请填入你的twitter ID",
			"id" => $shortname."_twitter_id",
			"std" => "",
			"type" => "text"),
	array(	"name" => "Facebook ID",
			"desc" => "请填入你的Facebook profile ID",
			"id" => $shortname."_facebook_id",
			"std" => "",
			"type" => "text"),
      			
  array(	"name"  => "页面底部设置",
					"type" => "heading"),    
  array(	"name" => "Footer text ",
          "desc" => "请填入您网站的版权信息",
            "id" => $shortname."_footer_text",
            "std" => "",
            "type" => "text")                  
);

?>